server.port=8080

# Configuracoes para rodar localmente no IntelliJ (O Azure substitui isso no deploy)
spring.datasource.url=jdbc:sqlserver://sqlserver-dimdim-carlos.database.windows.net:1433;database=nexus_verde_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=carlosadmin
spring.datasource.password=SenhaSuperSegura123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# Substitua pela chave real se quiser testar o monitoramento localmente
azure.application-insights.instrumentation-key=SUA_CHAVE_AQUI
